# Zadania z numpy 

In [1]:
import numpy as np

## Zadanie 1.1

In [12]:
wektor1 = np.random.seed(123)
wektor1 = np.random.uniform(-4, 4, 30)

In [33]:
wektor1[((wektor1>-2))&(wektor1<-1) | ((wektor1<2)&(wektor1>1))]

array([ 1.57175348, -1.71088532,  1.75575176,  1.47863791, -1.25457587,
        1.83239766,  1.90396325,  1.07520767,  1.7956426 ,  1.77954706,
       -1.41632869, -1.10569076, -1.65028763,  1.04780899])

In [34]:
wektor1[(wektor1>=0)].size

15

In [36]:
np.sum(wektor1>=0)

15

In [32]:
np.sum(np.absolute(wektor1))/wektor1.size

1.5260572308400788

In [37]:
np.mean(np.abs(wektor1))

1.5260572308400788

In [51]:
np.min((wektor1))

-3.5225768271234532

In [42]:
np.max(wektor1)

3.8461135870769239

### Wyznacz​ ​ wartość​ ​ najbliższą​ ​ i ​ ​ najdalsza​ ​ od​ ​ 0 ​ ​ (zachowując​ ​ jej​ ​ znak),

In [60]:
odleglosc = np.abs(wektor1-0)
odleglosc
np.argmin(odleglosc), np.argmax(odleglosc)
wektor1[np.argmin(odleglosc)] , wektor1[np.argmax(odleglosc)]

(-0.15254478812511252, 3.8461135870769239)

### Wyznacz​ ​ wartość​ ​ najbliższą​ ​ i ​ ​ najdalsza​ ​ od​ ​ 2 ​ ​ (zachowując​ ​ jej​ ​ znak)

In [62]:
odleglosc2 = np.abs(wektor1-2)
wektor1[np.argmin(odleglosc2)] , wektor1[np.argmax(odleglosc2)]

(1.9039632458562856, -3.5225768271234532)

### Wypisz na ekran część ułamkową wszystkich elementów

In [64]:
wektor1-wektor1.astype(int)

array([ 0.57175348, -0.71088532, -0.18518837,  0.41051815,  0.75575176,
       -0.61514832,  0.84611359,  0.47863791, -0.15254479, -0.86305985,
       -0.25457587,  0.83239766, -0.49142204, -0.52257683, -0.81564596,
        0.90396325, -0.54006616, -0.59638595,  0.25241099,  0.2546207 ,
        0.07520767,  0.79545435,  0.7956426 ,  0.88818809,  0.77954706,
       -0.41632869, -0.10569076, -0.17389415, -0.65028763,  0.04780899])

In [67]:
np.modf(wektor1)

(array([ 0.57175348, -0.71088532, -0.18518837,  0.41051815,  0.75575176,
        -0.61514832,  0.84611359,  0.47863791, -0.15254479, -0.86305985,
        -0.25457587,  0.83239766, -0.49142204, -0.52257683, -0.81564596,
         0.90396325, -0.54006616, -0.59638595,  0.25241099,  0.2546207 ,
         0.07520767,  0.79545435,  0.7956426 ,  0.88818809,  0.77954706,
        -0.41632869, -0.10569076, -0.17389415, -0.65028763,  0.04780899]),
 array([ 1., -1., -2.,  0.,  1., -0.,  3.,  1., -0., -0., -1.,  1., -0.,
        -3., -0.,  1., -2., -2.,  0.,  0.,  1.,  2.,  1.,  0.,  1., -1.,
        -1., -2., -1.,  1.]))

In [68]:
np.modf(wektor1)[0]

array([ 0.57175348, -0.71088532, -0.18518837,  0.41051815,  0.75575176,
       -0.61514832,  0.84611359,  0.47863791, -0.15254479, -0.86305985,
       -0.25457587,  0.83239766, -0.49142204, -0.52257683, -0.81564596,
        0.90396325, -0.54006616, -0.59638595,  0.25241099,  0.2546207 ,
        0.07520767,  0.79545435,  0.7956426 ,  0.88818809,  0.77954706,
       -0.41632869, -0.10569076, -0.17389415, -0.65028763,  0.04780899])

In [69]:
np.modf(wektor1)[1]

array([ 1., -1., -2.,  0.,  1., -0.,  3.,  1., -0., -0., -1.,  1., -0.,
       -3., -0.,  1., -2., -2.,  0.,  0.,  1.,  2.,  1.,  0.,  1., -1.,
       -1., -2., -1.,  1.])

In [71]:
wektor1 - np.trunc(wektor1)

array([ 0.57175348, -0.71088532, -0.18518837,  0.41051815,  0.75575176,
       -0.61514832,  0.84611359,  0.47863791, -0.15254479, -0.86305985,
       -0.25457587,  0.83239766, -0.49142204, -0.52257683, -0.81564596,
        0.90396325, -0.54006616, -0.59638595,  0.25241099,  0.2546207 ,
        0.07520767,  0.79545435,  0.7956426 ,  0.88818809,  0.77954706,
       -0.41632869, -0.10569076, -0.17389415, -0.65028763,  0.04780899])

### H. Postać znormalizowana do 1

In [73]:
((wektor1-np.min(wektor1))/(np.max(wektor1)-np.min(wektor1)))*2-1

array([ 0.38269625, -0.50827314, -0.63700783,  0.06751533,  0.43263682,
       -0.21086968,  1.        ,  0.35742295, -0.08531046, -0.2781575 ,
       -0.38442224,  0.45343994, -0.17728806, -1.        , -0.26528848,
        0.47286418, -0.73332828, -0.74861452,  0.02460209,  0.02520185,
        0.24792446,  0.71483149,  0.44346393,  0.19716386,  0.4390953 ,
       -0.42832498, -0.34401205, -0.63394237, -0.49182579,  0.24048795])

### I. Średnia​ ​ wartość​ ​ kwadratów​ ​ liczb​ ​ większych​ ​ od​ ​ 3 ​ ​ lub​ ​ mniejszych​ ​ od​ ​ -2

In [80]:
np.mean(wektor1[(wektor1>3) | (wektor1<-2)]**2)

8.3158595532060584

### J.

In [96]:
w=wektor1>=0
w.astype(int)
np.array(['ujemna','nieujemna'])[w.astype(int)]

array(['nieujemna', 'ujemna', 'ujemna', 'nieujemna', 'nieujemna', 'ujemna',
       'nieujemna', 'nieujemna', 'ujemna', 'ujemna', 'ujemna', 'nieujemna',
       'ujemna', 'ujemna', 'ujemna', 'nieujemna', 'ujemna', 'ujemna',
       'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna',
       'nieujemna', 'nieujemna', 'ujemna', 'ujemna', 'ujemna', 'ujemna',
       'nieujemna'], 
      dtype='<U9')

In [86]:
np.where(wektor1<0, 'ujemna', 'nieujemna')

array(['nieujemna', 'ujemna', 'ujemna', 'nieujemna', 'nieujemna', 'ujemna',
       'nieujemna', 'nieujemna', 'ujemna', 'ujemna', 'ujemna', 'nieujemna',
       'ujemna', 'ujemna', 'ujemna', 'nieujemna', 'ujemna', 'ujemna',
       'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna', 'nieujemna',
       'nieujemna', 'nieujemna', 'ujemna', 'ujemna', 'ujemna', 'ujemna',
       'nieujemna'], 
      dtype='<U9')

### O. 

In [97]:
np.floor(wektor1)+0.5

array([ 1.5, -1.5, -2.5,  0.5,  1.5, -0.5,  3.5,  1.5, -0.5, -0.5, -1.5,
        1.5, -0.5, -3.5, -0.5,  1.5, -2.5, -2.5,  0.5,  0.5,  1.5,  2.5,
        1.5,  0.5,  1.5, -1.5, -1.5, -2.5, -1.5,  1.5])

# 1.2

### A.

In [99]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.array([10,9,8,7,6,5,4,3,2,1])

In [102]:
r = (np.sum((x-np.mean(x))*(y-np.mean(y))))

In [111]:
p=(np.sum(np.sqrt((x-np.mean(x))**2))*(np.sum(np.sqrt((y-np.mean(y))**2))))

In [112]:
x_mean=np.mean(x)
y_mean=np.mean(y)

In [114]:
iloczyny = roznice_x*roznice_y
licznik = np.sum(iloczyny)
roznice_x2 = roznice_x**2
roznice_y2= roznice_y**2
mianownik = np.sqrt(np.sum(roznice_x2))*np.sum()

In [113]:
roznice_x= x- x_mean
roznice_y = y - y_mean

### Zadanie 1.3

In [115]:
x = np. random.uniform(-3,7,30)

In [117]:
np.mean(x)

2.1232627633763834

In [118]:
np.std(x)

2.3983528982612663

In [124]:
np.sqrt(np.var(x))

2.3983528982612663

In [121]:
d = (x - np.mean(x))/np.std(x)

In [122]:
np.mean(d)

-6.881069788041335e-18

In [123]:
np.std(d)

1.0000000000000002

### Zadanie 1.4

In [125]:
x = np. random.uniform(-3,7,30)
y = np. random.uniform(-3,2,30)

In [126]:
np.dot(x,y)

-35.168358154081432

In [127]:
np.matmul(np.matrix.transpose(x),y)

-35.168358154081432

In [128]:
np.matmul(x,y)

-35.168358154081432

### Zadanie 1.5 1.6 1.7

In [129]:
np.random.seed(123)
x = np.random.normal(size=10)
y=x+2

In [132]:
np.sqrt((np.sum((y-x)**2)/x.size))

2.0

In [133]:
np.sum(np.abs(y-x))/x.size

2.0

In [134]:
np.median(y-x)

2.0

### Zadanie 1.8

In [137]:
x = np.random.uniform(-3,7,30).astype(int)
y = np.random.uniform(-3,2,30).astype(int)

In [138]:
x, y 


(array([ 3,  4, -2,  2,  2, -1, -1,  3,  0,  3,  2,  0,  6,  5,  0, -2,  0,
         0,  4,  6,  0,  4,  2,  3, -1,  0,  0,  0,  2,  3]),
 array([-2, -2, -1,  0,  1,  0,  1, -1, -1, -1, -2,  1, -1,  0,  0,  0, -2,
         1,  1, -1, -1,  0,  1,  1, -1,  0,  1, -1,  0, -2]))

In [139]:
x-y

array([ 5,  6, -1,  2,  1, -1, -2,  4,  1,  4,  4, -1,  7,  5,  0, -2,  2,
       -1,  3,  7,  1,  4,  1,  2,  0,  0, -1,  1,  2,  5])

In [143]:
x[(x-y)!=0].size / x.size

0.9

### Zadanie 1.9

In [151]:
y = np.random.randint(0,2,10)
y_hat = np.random.uniform(0,1,10)
cross = -(np.sum((y*np.log(y_hat)+(1-y)*np.log(1-y_hat))))/y.size

In [152]:
cross


0.78422351517000677

### Zadanie 10

In [165]:
def lead(x,n):
    x_m=x[:x.size-n]
    x_n= np.repeat(np.NaN,n)
    
    return np.r_[x_m, x_n]

def lag(x,n):
    x_m=x[n:]
    x_n= np.repeat(np.NaN,n)
    
    return np.r_[x_n, x_m]

In [166]:
x = np.random.randint(0,2,10)
lead(x,5).size , lag(x,5).size


(10, 10)